name: build-os
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the OS image to build'
        required: true
        type: string
      base_release_name:
        description: 'The release name of the RPi OS base image (bullseye, bookworm)'
        required: true
        type: string
      base_image_variant:
        description: 'The name of the RPi OS base image variant (lite, desktop, or full)'
        required: true
        type: string
      base_release_date:
        description: 'The release date of the RPi OS base image'
        required: true
        type: string
      arch:
        description: 'The CPU architecture of the OS (armhf, arm64)'
        required: true
        type: string

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      OUTPUT_IMAGE_NAME: ${{ inputs.name }}-${{ inputs.base_release_name }}-${{ inputs.arch }}-${{ inputs.base_image_variant }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Determine Raspberry Pi OS base image URL
        id: rpi-os-image
        run: |
          case '${{ inputs.base_release_name }}' in
            'bookworm')
              IMAGE_RELEASE_CHANNEL='raspios'
              ;;
            'bullseye')
              IMAGE_RELEASE_CHANNEL='raspios_oldstable'
              ;;
            *)
              echo "Unknown release name: ${{ inputs.base_release_name }}"
              exit 1
              ;;
          esac
          IMAGE_REPO_GROUP="$IMAGE_RELEASE_CHANNEL"
          if [[ "${{ inputs.base_image_variant }}" != "desktop" ]]; then
            IMAGE_REPO_GROUP="${IMAGE_REPO_GROUP}_${{ inputs.base_image_variant }}"
          fi
          IMAGE_REPO_GROUP="${IMAGE_REPO_GROUP}_${{ inputs.arch }}"
          IMAGE_FILENAME="${{ inputs.base_release_date }}-raspios-${{ inputs.base_release_name }}-${{ inputs.arch }}"
          if [[ "${{ inputs.base_image_variant }}" != "desktop" ]]; then
            IMAGE_FILENAME="${IMAGE_FILENAME}-${{ inputs.base_image_variant }}"
          fi
          IMAGE_FILENAME="${IMAGE_FILENAME}.img.xz"
          IMAGE_URL="https://downloads.raspberrypi.com/$IMAGE_REPO_GROUP/images/$IMAGE_REPO_GROUP-${{ inputs.base_release_date }}/$IMAGE_FILENAME"
          echo "RPi OS image filename: $IMAGE_FILENAME"
          echo "image_filename=$IMAGE_FILENAME" >> $GITHUB_OUTPUT
          echo "RPi OS image URL: $IMAGE_URL"
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Set up base image caching
        uses: actions/cache@v4
        with:
          key: base-image-${{ steps.rpi-os-image.outputs.image_url }}
          path: .cache/base-images/${{ steps.rpi-os-image.outputs.image_filename }}

      - name: Download & decompress base image
        id: download-base
        run: |
          cached_download=".cache/base-images/${{ steps.rpi-os-image.outputs.image_filename }}"
          if [ -f "$cached_download" ]; then
          echo "Using cached image download at $cached_download..."
          else
            echo "Downloading ${{ steps.rpi-os-image.outputs.image_url }} to $cached_download..."
            curl -o "$cached_download" "${{ steps.rpi-os-image.outputs.image_url }}"
          fi

          tmpfile="$(mktemp -u)"
          mime="$(file -b --mime-type "$cached_download")"
          case "$mime" in
            application/octet-stream)
              echo "Copying $cached_download to $tmpfile..."
              cp "$cached_download" "$tmpfile"
              ;;
            application/gzip | application/x-gzip)
              echo "Extracting $cached_download to $tmpfile..."
              gunzip -c "$cached_download" > "$tmpfile"
              ;;
            application/x-xz)
              echo "Extracting $cached_download to $tmpfile..."
              unxz -c "$cached_download" > "$tmpfile"
              ;;
            *)
              echo -e "\033[0;31m### Error: Unknown image mimetype: $mime\033[0m"
              return 1
              ;;
          esac
          echo "mountable_image=$tmpfile" >> $GITHUB_OUTPUT

      - name: Expand & mount base image
        id: mount-base
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          truncate -s 8G $image
          echo ", +" | sfdisk -N 2 $image
          device="$(sudo losetup -fP --show $image)"
          sudo e2fsck -p -f "${device}p2"
          sudo resize2fs "${device}p2"
          echo "Mounting $device to /mnt/build..."
          sudo mkdir -p /mnt/build
          sudo mount "${device}p2" /mnt/build
          sudo mount "${device}p1" /mnt/build/boot
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      - name: Prepare for running OS build scripts
        run: |
          sudo apt-get install systemd-container qemu-user-static binfmt-support qemu-system-aarch64

      # Note: for performance reasons, we run most setup steps in a systemd-nspawn container. We
      # could boot it if we wanted (and it works fine for setup on a -lite base image), but for
      # some reason setup doesn't work on a -desktop base image (systemd calls during setup all fail
      # with a "Transport endpoint is not connected" error)
      - name: Run OS build scripts in an unbooted container
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          sysroot="/mnt/build"
          device="$(sudo ./tools/mount-image.sh "$image" "$sysroot")"
          echo "Booting a systemd-nspawn container for most of the setup..."
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/setup/setup-unbooted.sh
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      # Note: we need to boot the OS in a VM rather than a systemd-nspawn container because
      # `docker.service` can't start properly in the container due to its interaction with
      # the kernel (in bullseye Docker's use of iptables/nftables results in error
      # "Failed to initialize nft: Protocol not supported"; in bookworm Docker's use of cgroups
      # results in error "failed to start daemon: Devices cgroup isn't mounted").
      - name: Run OS build scripts in a booted VM
        env:
          # TODO: Work around incompatibility with bookworm base images
          # (see https://forums.raspberrypi.com/viewtopic.php?t=361643)
          MACHINE: 'raspi3b'
          RAM: 1G # raspi3b doesn't allow more than 1G
          DTB: ${{ inputs.base_release_name == 'bookworm' && 'bcm2710-rpi-3-b-plus.dtb' || 'bcm2710-rpi-3-b-plus.dtb' }}
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          sysroot="/mnt/build"
          device="$(sudo ./tools/mount-image.sh "$image" "$sysroot")"
          # Note: we can't boot an RPi 4B VM yet because support was only added in QEMU 9.0.0, which
          # is not yet provided by the ubuntu-24.04 runner!
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/ci-pre-vm-boot.sh
          cp -r $sysroot/boot .cache/
          sudo ./tools/unmount-image.sh "$device" "$sysroot"
          echo "Booting a ${{ env.MACHINE }} VM for remaining setup..."
          qemu-system-aarch64 \
            -machine ${{ env.MACHINE }} -cpu cortex-a72 -nographic \
            -dtb .cache/boot/${{ env.DTB }} -kernel .cache/boot/kernel8.img \
            -m ${{ env.RAM }} -smp 4 \
            -drive file=$image,if=sd,format=raw,index=0,media=disk \
            -append "rw earlyprintk loglevel=8 console=ttyAMA0,115200 dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2 rootdelay=1" \
            -netdev user,id=net0 -device usb-net,netdev=net0
          echo "The ${{ env.MACHINE }} VM has finished!"
          device="$(sudo ./tools/mount-image.sh "$image" "$sysroot")"
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/ci-post-vm-boot.sh
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/ci-pre-headless-boot.sh
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      - name: Run pishrink
        run: |
          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
          chmod a+x pishrink.sh
          sudo ./pishrink.sh -za \
            ${{ steps.download-base.outputs.mountable_image }} \
            ${{ env.OUTPUT_IMAGE_NAME }}.img

      - name: Upload image to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_IMAGE_NAME }}
          path: ${{ env.OUTPUT_IMAGE_NAME }}.img.gz
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
