name: build-os
on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the OS image to build'
        required: true
        type: string
      base_release_name:
        description: 'The release name of the RPi OS base image (bullseye, bookworm)'
        required: true
        type: string
      base_image_variant:
        description: 'The name of the RPi OS base image variant (lite, desktop, or full)'
        required: true
        type: string
      base_release_date:
        description: 'The release date of the RPi OS base image'
        required: true
        type: string
      arch:
        description: 'The CPU architecture of the OS (armhf, arm64)'
        required: true
        type: string

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      OUTPUT_IMAGE_NAME: ${{ inputs.name }}-${{ inputs.base_release_name }}-${{ inputs.arch }}-${{ inputs.base_image_variant }}
      SETUP_USER: pi
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Determine Raspberry Pi OS base image URL
        id: rpi-os-image
        run: |
          case '${{ inputs.base_release_name }}' in
            'bookworm')
              IMAGE_RELEASE_CHANNEL='raspios'
              ;;
            'bullseye')
              IMAGE_RELEASE_CHANNEL='raspios_oldstable'
              ;;
            *)
              echo "Unknown release name: ${{ inputs.base_release_name }}"
              exit 1
              ;;
          esac
          IMAGE_REPO_GROUP="$IMAGE_RELEASE_CHANNEL"
          if [[ "${{ inputs.base_image_variant }}" != "desktop" ]]; then
            IMAGE_REPO_GROUP="${IMAGE_REPO_GROUP}_${{ inputs.base_image_variant }}"
          fi
          IMAGE_REPO_GROUP="${IMAGE_REPO_GROUP}_${{ inputs.arch }}"
          IMAGE_FILENAME="${{ inputs.base_release_date }}-raspios-${{ inputs.base_release_name }}-${{ inputs.arch }}"
          if [[ "${{ inputs.base_image_variant }}" != "desktop" ]]; then
            IMAGE_FILENAME="${IMAGE_FILENAME}-${{ inputs.base_image_variant }}"
          fi
          IMAGE_FILENAME="${IMAGE_FILENAME}.img.xz"
          IMAGE_URL="https://downloads.raspberrypi.com/$IMAGE_REPO_GROUP/images/$IMAGE_REPO_GROUP-${{ inputs.base_release_date }}/$IMAGE_FILENAME"
          echo "RPi OS image filename: $IMAGE_FILENAME"
          echo "image_filename=$IMAGE_FILENAME" >> $GITHUB_OUTPUT
          echo "RPi OS image URL: $IMAGE_URL"
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT

      - name: Set up base image caching
        uses: actions/cache@v4
        with:
          key: base-image-${{ steps.rpi-os-image.outputs.image_url }}
          path: .cache/base-images/${{ steps.rpi-os-image.outputs.image_filename }}

      - name: Download & decompress base image
        id: download-base
        run: |
          cached_download=".cache/base-images/${{ steps.rpi-os-image.outputs.image_filename }}"
          if [ -f "$cached_download" ]; then
          echo "Using cached image download at $cached_download..."
          else
            echo "Downloading ${{ steps.rpi-os-image.outputs.image_url }} to $cached_download..."
            curl -o "$cached_download" "${{ steps.rpi-os-image.outputs.image_url }}"
          fi

          tmpfile="$(mktemp -u)"
          mime="$(file -b --mime-type "$cached_download")"
          case "$mime" in
            application/octet-stream)
              echo "Copying $cached_download to $tmpfile..."
              cp "$cached_download" "$tmpfile"
              ;;
            application/gzip | application/x-gzip)
              echo "Extracting $cached_download to $tmpfile..."
              gunzip -c "$cached_download" > "$tmpfile"
              ;;
            application/x-xz)
              echo "Extracting $cached_download to $tmpfile..."
              unxz -c "$cached_download" > "$tmpfile"
              ;;
            *)
              echo -e "\033[0;31m### Error: Unknown image mimetype: $mime\033[0m"
              return 1
              ;;
          esac
          echo "mountable_image=$tmpfile" >> $GITHUB_OUTPUT

      - name: Expand & mount base image
        id: mount-base
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          truncate -s 8G $image
          echo ", +" | sfdisk -N 2 $image
          device="$(sudo losetup -fP --show $image)"
          sudo e2fsck -p -f "${device}p2"
          sudo resize2fs "${device}p2"
          echo "Mounting $device to /mnt/build..."
          sudo mkdir -p /mnt/build
          sudo mount "${device}p2" /mnt/build
          sudo mount "${device}p1" /mnt/build/boot
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      - name: Prepare for running OS build scripts
        run: |
          sudo apt-get install systemd-container qemu-user-static binfmt-support qemu-system-aarch64

      # Note: for performance reasons, we run most setup steps in a systemd-nspawn container. We
      # could boot it if we wanted (and it works fine for setup on a -lite base image), but for
      # some reason setup doesn't work on a -desktop base image (systemd calls during setup all fail
      # with a "Transport endpoint is not connected" error)
      - name: Run OS build scripts in an unbooted container
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          sysroot="/mnt/build"
          device="$(sudo ./tools/mount-image.sh "$image" "$sysroot")"
          echo "Booting a systemd-nspawn container for most of the setup..."
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            su - ${{ env.SETUP_USER }} /run/os-setup/setup/setup-unbooted.sh
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      - name: Prepare to run remaining OS build scripts in a booted VM
        id: prepare-vm
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          sysroot="/mnt/build"
          device="$(sudo ./tools/mount-image.sh "$image" "$sysroot")"
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/ci-pre-vm-boot.sh ${{ env.SETUP_USER }}
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      - name: Set up arm64 VM kernel caching
        uses: actions/cache@v4
        env:
          KERNEL_VERSION: 6.6.32
        with:
          key: kernel-linux-virt-arm64-${{ env.KERNEL_VERSION }}
          path: .cache/vm-kernels/kernel-linux-virt-arm64-${{ env.KERNEL_VERSION }}.img

      - name: Build or use arm64 VM kernel
        id: vm-kernel
        env:
          KERNEL_VERSION: 6.6.32
        run: |
          cached_kernel=".cache/vm-kernels/kernel-linux-virt-arm64-${{ env.KERNEL_VERSION }}.img"
          if [ -f "$cached_kernel" ]; then
            echo "Using cached image kernel at $cached_kernel..."
          else
            # From https://gist.github.com/cGandom/23764ad5517c8ec1d7cd904b923ad863
            echo "Compiling kernel ${{ env.KERNEL_VERSION }} to $cached_kernel..."
            sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            kernel_dir="linux-${{ env.KERNEL_VERSION }}"
            curl -s -L "https://cdn.kernel.org/pub/linux/kernel/v6.x/$kernel_dir.tar.xz" | \
              tar xvJf - -C "$kernel_dir"
            export ARCH=arm64
            export CROSS_COMPILE=/bin/aarch64-linux-gnu-
            make -C "$kernel_dir" defconfig # make a .config file
            make -C "$kernel_dir" kvm_guest.config # use the kvm_guest config as the base defconfig
            make -C "$kernel_dir" -j8 # build the kernel
            cp "$kernel_dir/arch/arm64/boot/Image" "$cached_kernel"
          fi
          echo "kernel_image=$cached_kernel" >> $GITHUB_OUTPUT

      # Note: we need to boot the OS in a VM rather than a systemd-nspawn container because
      # `docker.service` can't start properly in the container due to its interaction with
      # the kernel (in bullseye Docker's use of iptables/nftables results in error
      # "Failed to initialize nft: Protocol not supported"; in bookworm Docker's use of cgroups
      # results in error "failed to start daemon: Devices cgroup isn't mounted").
      - name: Run OS build scripts in a booted VM
        env:
          # We use the `virt` hardware type because the `raspi3b` hardware type doesn't work with
          # bookworm, and because the `raspi4b` hardware type is only available in QEMU 9 (which
          # isn't available in ubuntu-24.04 but can be installed in an Arch Linux container,
          # e.g. with addnab/docker-run-action@v3) and doesn't seem to support the `usb-net` network
          # device type, and definitely doesn't support PCI or Ethernet.
          MACHINE: 'virt'
          RAM: 4G
          FS_IMAGE: ${{ steps.download-base.outputs.mountable_image }}
        run: |
          # From https://gist.github.com/cGandom/23764ad5517c8ec1d7cd904b923ad863
          qemu-system-aarch64 \
            -machine ${{ env.MACHINE }} -cpu cortex-a72 -nographic \
            -smp 4 -m ${{ env.RAM }} \
            -kernel ${{ steps.vm-kernel.outputs.kernel_image }} \
            -drive file=${{ env.FS_IMAGE }},if=none,id=hd0,format=raw,index=0,cache=writeback \
            -device virtio-blk,drive=hd0,bootindex=0 \
            -netdev user,id=net0,hostfwd=tcp::2222-:22 \
            -device virtio-net-pci,netdev=net0 \
            -monitor telnet:127.0.0.1:5555,server,nowait

      - name: Clean up after VM boot
        run: |
          image="${{ steps.download-base.outputs.mountable_image }}"
          sysroot="/mnt/build"
          device="$(sudo ./tools/mount-image.sh "$image" "$sysroot")"
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/ci-post-vm-boot.sh ${{ env.SETUP_USER }}
          sudo systemd-nspawn --directory $sysroot \
            --bind "$(pwd)"/os-setup:/run/os-setup \
            /run/os-setup/ci-pre-headless-boot.sh
          sudo ./tools/unmount-image.sh "$device" "$sysroot"

      - name: Run pishrink
        run: |
          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
          chmod a+x pishrink.sh
          sudo ./pishrink.sh -za \
            ${{ steps.download-base.outputs.mountable_image }} \
            ${{ env.OUTPUT_IMAGE_NAME }}.img

      - name: Upload image to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_IMAGE_NAME }}
          path: ${{ env.OUTPUT_IMAGE_NAME }}.img.gz
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
