---
name: build-os-bullseye
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  merge_group:
  workflow_dispatch:

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        variant_name:
          - lite
          - desktop
        arch:
          - arm64
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-os.yml
    secrets: inherit
    with:
      name: rpi-forklift-demo
      base_release_name: bullseye
      base_image_variant: ${{ variant_name }}
      base_release_date: 2024-03-12
      arch: ${{ matrix.arch }}
