name: check-pallet

on:
  push:
    branches:
      - main
      - edge
      - beta
      - stable
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        forklift-version: [0.7.2-alpha.6]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Forklift
        uses: PlanktoScope/setup-forklift@v1
        with:
          version: ${{ matrix.forklift-version }}

      - name: Run Forklift checks
        run: |
          # FIXME: dev plt cache-all should first cache repos instead of just failing with an error
          # that repos are not yet cached. Also, check should automatically cache needed
          # dependencies.
          forklift dev plt cache-repo
          forklift dev plt check

      - name: Make Forklift deployment plan
        run: forklift dev plt plan
